refs #114: additions mentioned in my comments
sparkfabrik/company-playbook pull request #128
Opened 2022-12-28 16:36 UTC by stickgrinder

@paolomainardi here is my personal additions plus a bit of rephrasing here and there, as mentioned in my comments on documentation and project-level checkmarks.

I guess a run on grammarly may help, I didn't to it yet.
Let me know if you need me to change stuff.

2022-12-28 21:20 UTC, aijcoa commented on content/procedures/universal-dod.md
> +To better **match our standards** in all the **technologies** we work with, we have in place **several practices** to help **everyone** being **successful**:
This was sentence was fine, `to be` makes sense.

2022-12-28 21:22 UTC, aijcoa commented on content/procedures/universal-dod.md
> +All this helps us shaping a **better product**, reducing the **cognitive load** needed to **build, test, and deliver** **digital products** compatible with the **company standards**.
All this helps us shaping -> All this helps us **to shape**

2022-12-28 21:23 UTC, aijcoa commented on content/procedures/universal-dod.md
> +In simple words a _Definition of Done_ is **a checklist of non-functional requirements** that ensure to be on the **right path** and understand if a **task is actually done** or if it needs more work
that ensure -> **to ensure**

2022-12-28 21:25 UTC, aijcoa commented on content/procedures/universal-dod.md
> +This is a general list of **non-functional rules that apply to every scenarios**; with _non-functional_ we mean **they are not bound to specific use cases** but to the **project itself**, **agreed**
every scenarios > every scenario

2022-12-28 21:26 UTC, aijcoa commented
Added a couple of suggestions for the grammar, but it all looks good. I can take a look at the rest of the playbook this week if you'd like 👍

2023-01-09 12:31 UTC, paolomainardi requested changes
Thanks a lot @aijcoa 

@stickgrinder, thanks for the addition; once the wording fixes are in place, we can merge this.

2023-01-09 12:53 UTC, stickgrinder commented
@paolomainardi I fixed all mistakes (thanks @aijcoa) and moved the file to the "Policies" section (since DoD is actually a policy).
Thanks

2023-01-09 18:51 UTC, paolomainardi approved these changes
LGTM

2023-01-09 18:51 UTC, merged

2023-01-09 18:52 UTC, paolomainardi commented
Done! Thanks @stickgrinder and @aijcoa